<?php
namespace app\portal\model;

use think\Model;
use Faker\Factory;
use app\portal\model\AdminHouseModel;
use think\Db;
class AdminRobotModel extends Model
{
    protected $pk = 'mid';
    protected $table = 'cmf_portal_robot';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function faker_create($data,$child_rid)
    {
       Vendor('faker/v1.7.1/src/autoload.php');

        $faker = Factory::create('zh_CN');

        if($data['rid'] === '0')
        {
            $rids = $child_rid;
        }

        if($data['aid'] === '0')
        {
            $aids = Db::name('protal_role')
                    ->where('status',1)
                    ->field('id')
                    ->select();

        }

        $date = date('Y-m-d');
        $create['stime_str'] = $data['stime_str'];
        $create['etime_str'] = $data['etime_str'];
        $create['week'] = implode(',',array_keys($data['week']));
        $create['stime'] = strtotime($date.' '.$data['stime_str']);
        $create['etime'] = strtotime($date.' '.$data['etime_str']);


        //如果rid 和 aid 都为  0  则房间和用户组都需要随机选择
        if($data['rid'] === '0' && $data['aid'] === '0')
        {
            for($i=0;$i<intval($data['number']);$i++)
            {
                $shuaid = $aids->shuffle()->shift();
                $create['aid'] =$shuaid['id'];
                shuffle($rids);
                $create['rid'] = $rids[0];

                $create['username'] = $faker->name;

                //插入数据库

                $this->allowField(true)->data($create, true)->isUpdate(false)->save();
            }
        }else{
            if($data['rid'] !== '0' && $data['aid'] === '0')
            {
                for($i=0;$i<intval($data['number']);$i++)
                {
                    $shuaid = $aids->shuffle()->shift();
                    $create['aid'] =$shuaid['id'];
                    $create['rid'] = $data['rid'];

                    $create['username'] = $faker->name;

                    //插入数据库

                    $this->allowField(true)->data($create, true)->isUpdate(false)->save();
                }
            }else if($data['rid'] === '0' && $data['aid'] !== '0'){
                for($i=0;$i<intval($data['number']);$i++)
                {
                    $create['aid'] = $data['aid'];
                    shuffle($rids);
                    $create['rid'] = $rids[0];
                    $create['username'] = $faker->name;

                    //插入数据库

                    $this->allowField(true)->data($create, true)->isUpdate(false)->save();
                }
            }else{
                for($i=0;$i<intval($data['number']);$i++)
                {
                    $create['aid'] = $data['aid'];
                    $create['rid'] = $data['rid'];
                    $create['username'] = $faker->name;

                    //插入数据库

                    $this->allowField(true)->data($create, true)->isUpdate(false)->save();
                }
            }
        }

    }

}