<?php
// +----------------------------------------------------------------------
// | ThinkCMF [ WE CAN DO IT MORE SIMPLE ]
// +----------------------------------------------------------------------
// | Copyright (c) 2013-2018 http://www.thinkcmf.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: 老猫 <thinkcmf@126.com>
// +----------------------------------------------------------------------
namespace app\portal\model;

use think\Model;
use traits\model\SoftDelete;
class AdminHousevModel extends Model
{
    use SoftDelete;
    protected $deleteTime = 'delete_time';
    protected $table = 'cmf_room_video_set';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


}